# This job includes linting, unit tests and code coverage, copied and adapted from the template repository

jobs:
- job: unitTests
  displayName: 'Application: lint, test, check code coverage'
  pool:
    vmImage: '$(vmImageName)'

  steps:
  - task: UsePythonVersion@0
    displayName: 'Determine Python version'
    inputs:
      versionSpec: '3.9'
      architecture: 'x64'

  - script: |
      python -m pip install -r requirements.txt
      python -m pip install pytest-cov
    displayName: 'Install requirements'

  - script: |
      python -m pip install flake8
      flake8 $(pythonLintFolder)
    displayName: 'Run lint tests'

  - script: |
      python -m pytest --doctest-modules --junitxml=junit/test-results.xml --cov-report=xml --cov=.. $(pythonTestFolder)
    displayName: 'Run unit tests with pytest'

  - task: PublishTestResults@2
    displayName: 'Publish test results'
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Publish test results for Python $(python.version)'

  - task: PublishCodeCoverageResults@2
    displayName: 'Publish code coverage'
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'